server:
  port: 8080

mybatis:
  datasource:
    driver-class: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://47.101.203.238:3306/pay_platform?characterEncoding=utf8&useSSL=false
    data-base-user: root
    data-base-password: 1qaz@WSX
    initial-pool-size: 5
    min-idle: 5
    max-pool-size: 20
    max-wait-millis: 6000